# Generated by Django 4.2.4 on 2023-10-26 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='new/')),
            ],
            options={
                'verbose_name': 'Rasmlar',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher', models.CharField(max_length=300, verbose_name="O'qituvchilar soni")),
                ('student', models.CharField(max_length=200, verbose_name="O'quvchilar soni")),
                ('otm', models.CharField(max_length=40, verbose_name="OTM ga kirish ko'rsatkichi")),
                ('acceptance', models.CharField(max_length=40, verbose_name='Qabulga kelib tushgan arizalar soni')),
            ],
            options={
                'verbose_name': "O'zgartirish",
            },
        ),
    ]
